# Generated by Django 2.1.4 on 2019-03-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vidicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidicap_model', models.CharField(choices=[('4', 'Vidicap Touch'), ('2', 'Vidicap Mini'), ('3', 'Vidicap Stream'), ('1', 'Vidicap HD')], max_length=15, verbose_name='Модель Vidicap')),
                ('sell_date', models.DateField()),
                ('set_up_date', models.DateField(default=None)),
                ('set_up_place', models.CharField(max_length=300, verbose_name='Место устрановки')),
                ('set_up_complete', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=1500)),
            ],
        ),
    ]
