# Generated by Django 2.1.7 on 2019-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vidicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidicap',
            name='set_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vidicap',
            name='vidicap_model',
            field=models.CharField(choices=[('3', 'Vidicap Stream'), ('2', 'Vidicap Mini'), ('1', 'Vidicap HD'), ('4', 'Vidicap Touch')], max_length=15, verbose_name='Модель Vidicap'),
        ),
    ]
