# Generated by Django 2.1.7 on 2019-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190316_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidicap',
            name='set_up_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='vidicap',
            name='vidicap_model',
            field=models.CharField(choices=[('1', 'Vidicap HD'), ('2', 'Vidicap Mini'), ('4', 'Vidicap Touch'), ('3', 'Vidicap Stream')], max_length=15, verbose_name='Модель Vidicap'),
        ),
    ]
