# Generated by Django 2.1.7 on 2019-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190316_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidicap',
            name='set_up_date',
        ),
        migrations.AlterField(
            model_name='vidicap',
            name='vidicap_model',
            field=models.CharField(choices=[('3', 'Vidicap Stream'), ('2', 'Vidicap Mini'), ('1', 'Vidicap HD'), ('4', 'Vidicap Touch')], max_length=15, verbose_name='Модель Vidicap'),
        ),
    ]
