# Generated by Django 2.1.7 on 2019-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190316_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_number', models.CharField(max_length=150, verbose_name='Номер конкурса')),
                ('tender_lot', models.CharField(max_length=50, verbose_name='Номер лота')),
                ('budget', models.CharField(max_length=50, verbose_name='Тип бюджета')),
                ('date_podacha', models.DateField()),
                ('date_tender', models.DateField()),
                ('buyer', models.CharField(max_length=150, verbose_name='Покупатель')),
                ('customer', models.CharField(max_length=150, verbose_name='Заказчик')),
                ('sum_offer', models.IntegerField(default=0, verbose_name='Сумма предложения')),
                ('note', models.CharField(max_length=2500, verbose_name='Примечание')),
            ],
        ),
        migrations.AlterField(
            model_name='vidicap',
            name='vidicap_model',
            field=models.CharField(choices=[('Vidicap Mini', '2'), ('Vidicap HD', '1'), ('Vidicap Stream', '3'), ('Vidicap Touch', '4')], max_length=15, verbose_name='Модель Vidicap'),
        ),
    ]
